<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NetTopologySuite.IO.GeoJSON4STJ" Version="4.0.0" />
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit.Analyzers"/>
        <PackageReference Include="NUnit3TestAdapter"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SkyTower.Infrastructure\SkyTower.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="MesoscaleDiscussions\TestFiles\2026-MD0087.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="MesoscaleDiscussions\TestFiles\2026-MD0089.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="MesoscaleDiscussions\TestFiles\2026-MD0090.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="MesoscaleDiscussions\TestFiles\2026-MD0006.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="MesoscaleDiscussions\TestFiles\2025-MD2288.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="MesoscaleDiscussions\TestFiles\2026-MD0006-Discussion.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <None Remove="MesoscaleDiscussions\TestFiles\ExpectedDiscussions.json"/>
        <Content Include="MesoscaleDiscussions\TestFiles\ExpectedDiscussions.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <None Remove="MesoscaleDiscussions\TestFiles\ExpectedBoundaries.json" />
        <Content Include="MesoscaleDiscussions\TestFiles\ExpectedBoundaries.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <None Remove="MesoscaleDiscussions\TestFiles\ExpectedSummaries.json" />
        <Content Include="MesoscaleDiscussions\TestFiles\ExpectedSummaries.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
